url          = require('url')
query_string = require('querystring')
action_types = ['opened', 'synchronize', 'reopened']
event_types  = ['pull_request']

bamboo_user  = process.env.bamboo_user
bamboo_pass  = process.env.bamboo_pass
github_api_token = process.env.github_api_token

module.exports = (robot) ->
  robot.router.post "/hubot/trigger-bamboo", (req, res) ->

    console.log "---"
    console.log "Request received: #{req.url}"

    # Extract Bamboo plan variables from query url
    query      = query_string.parse(url.parse(req.url).query)
    bamboo_url = query.bamboo
    build_key  = query.buildKey
    if !bamboo_url? or !build_key?
      console.log "Bad request. Missing parameters in query string"
      res.writeHead 400
      res.end "Missing parameters in query string\n"
      return

    # Extract pull request info from webhook headers and payload
    payload     = req.body
    action_type = payload.action
    event_type  = req.headers["x-github-event"]

    try
      if event_type in event_types && action_type in action_types

        # Webhook was generated by valid pull request. Attempt to queue Bamboo PR build
        console.log "Processing #{event_type} event in repo #{payload.pull_request.html_url}. Action: #{action_type}"
        robot.http("#{bamboo_url}/rest/api/latest/queue/#{build_key}?" +
                   "bamboo.variable.pull_ref=#{payload.pull_request.head.ref}&" +
                   "bamboo.variable.pull_sha=#{payload.pull_request.head.sha}&" +
                   "bamboo.variable.pull_num=#{payload.number}&" +
                   "bamboo.variable.git_repo_url=#{payload.repository.clone_url}")
          .auth(bamboo_user, bamboo_pass)
          .header('Accept', 'application/json')
          .post() (err, res, body) ->
            if err
              console.log "Encountered an error :( #{err}"
            else
              json_body = JSON.parse body

              # Determine whether build was successfully queued and update GitHub PR status accordingly
              if !json_body.hasOwnProperty("status-code")
                robot.http(payload.pull_request.statuses_url)
                  .header('Authorization', "token #{github_api_token}")
                  .post('{"state": "pending", "context": "bamboo", "description": "A Bamboo build has been queued", "target_url": "' +
                        "#{bamboo_url}/browse/#{json_body.buildResultKey}\"}")
              else
                console.log body
                robot.http(payload.pull_request.statuses_url)
                  .header('Authorization', "token #{github_api_token}")
                  .post('{"state": "failure", "context": "bamboo", "description": "' + "#{json_body.message}" + '", "target_url": "' +
                        "#{bamboo_url}/browse/#{build_key}\"}")
      else if event_type not in event_types
        console.log "Ignoring #{event_type} event in repo #{payload.pull_request.html_url}. Only pull_request events are handled"
      else
        console.log "Pull request #{payload.pull_request.html_url} was #{action_type}. Ignoring event as no code changes were made"
    catch error
      console.log "#{error}. Request: #{req.body}"

    res.end "okay"
